--- #YAML:1.0
name: Module-Locate
version: 1.3
license: perl
distribution_type: module
requires:
  Carp: 0
  File::Spec::Functions: 0
  IO::File: 0
  perl: 5.6.1
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Module::Locate:
    file: lib/Module/Locate.pm
    version: 1.3
generated_by: Module::Build version 0.21
