--- #YAML:1.0
name: Module-Locate
version: 1.6
author:
  - Dan Brook C<< <cpan@broquaint.com> >>
abstract: locate modules in the same fashion as C<require> and C<use>
license: perl
generated_by: Module::Build version 0.261, without YAML.pm
